import { PhotoItem } from './mediaTypes';

export const PHOTOS_DATA: PhotoItem[] = [
  {
    id: 'photo-1',
    title: 'ARPS Agartala Administrative & Academic Complex',
    category: 'Campus',
    imageUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/campus/admin_complex.jpg',
    date: '2024-11-15',
    description: 'Frontage of Assam Rifles Public School, Agartala set amidst manicured cantonment gardens and tall pine trees.',
    tags: ['Campus', 'Building', 'Cantonment', 'Facade'],
    featured: true,
  },
  {
    id: 'photo-2',
    title: 'Inter-School Cricket Championship Winners',
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/sports/cricket_winners.jpg',
    date: '2024-10-22',
    description: 'ARPS Agartala senior cricket squad celebrating victory in the state inter-school tournament.',
    tags: ['Cricket', 'Sports', 'Championship', 'Trophy'],
    featured: true,
  },
  {
    id: 'photo-3',
    title: 'Senior Secondary Chemistry Analytical Lab',
    category: 'Laboratories',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/laboratories/chemistry_lab.jpg',
    date: '2024-09-18',
    description: 'Senior secondary students conducting volumetric analysis and chemical titrations under faculty supervision.',
    tags: ['Chemistry', 'Lab', 'Science', 'Class XII'],
    featured: true,
  },
  {
    id: 'photo-4',
    title: '77th Independence Day Ceremonial March Past',
    category: 'Ceremonial',
    imageUrl: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/ceremonial/independence_day.jpg',
    date: '2024-08-15',
    description: 'Disciplined student parade marching in immaculate uniforms with the National Tricolor hoisted on the assembly ground.',
    tags: ['Independence Day', 'Drill', 'Parade', 'Patriotism'],
    featured: true,
  },
  {
    id: 'photo-5',
    title: 'Science, Robotics & AI Innovation Fair',
    category: 'Activities',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/activities/robotics_expo.jpg',
    date: '2024-11-08',
    description: 'Middle and secondary students demonstrating working Arduino robotics prototypes and eco-friendly models.',
    tags: ['Science', 'AI', 'Robotics', 'Innovation'],
    featured: false,
  },
  {
    id: 'photo-6',
    title: 'High-Speed Computer & Information Technology Wing',
    category: 'Laboratories',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/laboratories/computer_lab.jpg',
    date: '2024-10-05',
    description: 'Fully networked 40-terminal IT laboratory equipped with broadband internet and Python programming workstations.',
    tags: ['Computers', 'Coding', 'IT Lab', 'Technology'],
    featured: false,
  },
  {
    id: 'photo-7',
    title: 'Assam Rifles NCC Army Wing Cadets Drill Practice',
    category: 'NCC',
    imageUrl: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/ncc/drill_practice.jpg',
    date: '2024-09-29',
    description: 'NCC cadets rehearsing weapon drill and tactical marching squad techniques on the cantonment parade ground.',
    tags: ['NCC', 'Military Drill', 'Assam Rifles', 'Discipline'],
    featured: true,
  },
  {
    id: 'photo-8',
    title: 'Annual Cultural Gala & Rabindra Jayanti Celebrations',
    category: 'Cultural',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/cultural/annual_day_dance.jpg',
    date: '2024-05-09',
    description: 'Students performing traditional Manipuri and Tripura folk dance recitals at the school auditorium.',
    tags: ['Dance', 'Cultural', 'Auditorium', 'Tradition'],
    featured: false,
  },
  {
    id: 'photo-9',
    title: 'Central Library & Reading Hall',
    category: 'Campus',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/campus/library_hall.jpg',
    date: '2024-10-12',
    description: 'Peaceful reading repository housing over 4,500 reference titles, CBSE journals, and digital periodicals.',
    tags: ['Library', 'Books', 'Reading', 'Academics'],
    featured: false,
  },
  {
    id: 'photo-10',
    title: 'Annual Athletic Meet 100m Sprint Finals',
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/sports/athletic_sprint.jpg',
    date: '2024-12-14',
    description: 'House champions battling for gold in the senior boys 100m sprint race on the synthetic athletic track.',
    tags: ['Athletics', 'Track & Field', 'Sprint', 'Sports Day'],
    featured: false,
  },
  {
    id: 'photo-11',
    title: 'Smart Digital Multimedia Classroom in Session',
    category: 'Activities',
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/activities/smart_classroom.jpg',
    date: '2024-11-20',
    description: 'Interactive touch-screen display teaching mathematics and 3D geometry concepts in junior wing.',
    tags: ['Smart Class', 'Interactive', 'Teaching', 'Digital'],
    featured: false,
  },
  {
    id: 'photo-12',
    title: 'Investiture Ceremony: Student Council Badge Handover',
    category: 'Ceremonial',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/photos/ceremonial/investiture.jpg',
    date: '2024-07-25',
    description: 'Head Boy, Head Girl, and House Captains receiving their sashes and solemnizing the oath of duty.',
    tags: ['Investiture', 'Leadership', 'Prefects', 'Student Council'],
    featured: true,
  },
];
