import { VideoItem } from './mediaTypes';

export const VIDEOS_DATA: VideoItem[] = [
  {
    id: 'vid-1',
    title: 'ARPS Agartala: Virtual Campus Tour & Facilities Showcase',
    category: 'Campus Tour',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Clean embed link
    thumbnailUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/videos/campus_tour.mp4',
    duration: '4:35',
    date: '2024-11-01',
    description: 'A guided cinematic walkthrough exploring our 23,876 sq. meter cantonment grounds, hi-tech science laboratories, IT wing, and lush sports field.',
    type: 'youtube',
    tags: ['Campus Tour', 'Infrastructure', 'Laboratories', 'Sports Ground'],
    featured: true,
  },
  {
    id: 'vid-2',
    title: '77th Independence Day Ceremonial Parade & March Past',
    category: 'Ceremonial',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/videos/independence_day_parade.mp4',
    duration: '6:12',
    date: '2024-08-15',
    description: 'Highlights of the ceremonial drill, National Flag hoisting, guard of honour, and patriotic assembly presented by ARPS students and NCC cadets.',
    type: 'youtube',
    tags: ['Independence Day', 'Military Drill', 'Tricolor', 'Parade'],
    featured: true,
  },
  {
    id: 'vid-3',
    title: 'Annual Day 2024: "Sur & Sargam" Cultural Extravaganza',
    category: 'Events',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/videos/annual_day_2024.mp4',
    duration: '8:45',
    date: '2024-05-12',
    description: 'Vibrant musical orchestra, Manipuri classical dance, patriotic theater drama, and prize distribution ceremony at Rabindra Satabarshiki Bhawan.',
    type: 'youtube',
    tags: ['Annual Day', 'Cultural', 'Music', 'Dance', 'Drama'],
    featured: true,
  },
  {
    id: 'vid-4',
    title: 'Assam Rifles NCC Army Wing Cadets Weapon & Obstacle Drill',
    category: 'Ceremonial',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579208570378-8c970854bc23?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/videos/ncc_obstacle_drill.mp4',
    duration: '5:20',
    date: '2024-09-28',
    description: 'Demonstration of physical endurance, obstacle clearing, tent-pitching, and military discipline by ARPS Agartala NCC boys and girls.',
    type: 'youtube',
    tags: ['NCC', 'Army Wing', 'Obstacle Training', 'Military'],
    featured: false,
  },
  {
    id: 'vid-5',
    title: 'Annual Inter-House Athletics & Football Championship Finals',
    category: 'Sports',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/videos/sports_finals.mp4',
    duration: '7:18',
    date: '2024-12-16',
    description: 'Thrilling moments from the senior boys football final (Subhash House vs Gandhi House) and the 4x100m relay track events.',
    type: 'youtube',
    tags: ['Sports', 'Football', 'Athletics', 'Houses'],
    featured: false,
  },
  {
    id: 'vid-6',
    title: 'Science & Robotics Exhibition: Student Inventions & AI Models',
    category: 'Academics',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    localPath: '/media/videos/science_exhibition.mp4',
    duration: '4:50',
    date: '2024-11-10',
    description: 'Interviews with student innovators explaining solar smart irrigation circuits, bamboo water filters, and Python AI algorithms.',
    type: 'youtube',
    tags: ['Science Fair', 'Robotics', 'Invention', 'Exhibition'],
    featured: false,
  },
];
